apiVersion: external-secrets.io/v1beta1
kind: SecretStore # This one can be ClusterSecretStore for a cluster level resources
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault-server.vault.svc.cluster.local:8200" # Calling local vault running in same cluster
      path: "app"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "1e62e9f0-1c21-f9c1-4a58-9a8c9394ebd1"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
